/**
 * ServiceFinder API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package hu.bme.onlab.model;

import hu.bme.onlab.model.Authority;
import hu.bme.onlab.model.Principal;
import hu.bme.onlab.model.SessionDetails;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class User  {
  
  @SerializedName("authenticated")
  private Boolean authenticated = null;
  @SerializedName("authorities")
  private List<Authority> authorities = null;
  @SerializedName("credentials")
  private String credentials = null;
  @SerializedName("details")
  private SessionDetails details = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("principal")
  private Principal principal = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getAuthenticated() {
    return authenticated;
  }
  public void setAuthenticated(Boolean authenticated) {
    this.authenticated = authenticated;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Authority> getAuthorities() {
    return authorities;
  }
  public void setAuthorities(List<Authority> authorities) {
    this.authorities = authorities;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCredentials() {
    return credentials;
  }
  public void setCredentials(String credentials) {
    this.credentials = credentials;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public SessionDetails getDetails() {
    return details;
  }
  public void setDetails(SessionDetails details) {
    this.details = details;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Principal getPrincipal() {
    return principal;
  }
  public void setPrincipal(Principal principal) {
    this.principal = principal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return (authenticated == null ? user.authenticated == null : authenticated.equals(user.authenticated)) &&
        (authorities == null ? user.authorities == null : authorities.equals(user.authorities)) &&
        (credentials == null ? user.credentials == null : credentials.equals(user.credentials)) &&
        (details == null ? user.details == null : details.equals(user.details)) &&
        (name == null ? user.name == null : name.equals(user.name)) &&
        (principal == null ? user.principal == null : principal.equals(user.principal));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (authenticated == null ? 0: authenticated.hashCode());
    result = 31 * result + (authorities == null ? 0: authorities.hashCode());
    result = 31 * result + (credentials == null ? 0: credentials.hashCode());
    result = 31 * result + (details == null ? 0: details.hashCode());
    result = 31 * result + (name == null ? 0: name.hashCode());
    result = 31 * result + (principal == null ? 0: principal.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("  authenticated: ").append(authenticated).append("\n");
    sb.append("  authorities: ").append(authorities).append("\n");
    sb.append("  credentials: ").append(credentials).append("\n");
    sb.append("  details: ").append(details).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  principal: ").append(principal).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
