/**
 * ServiceFinder API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package hu.bme.onlab.model.post;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Calendar;

import io.swagger.annotations.*;

import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class ListPostsRequest implements Serializable {

  @SerializedName("page")
  private BigDecimal page = null;
  @SerializedName("pageSize")
  private BigDecimal pageSize = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("priceMin")
  private Integer priceMin = null;
  @SerializedName("priceMax")
  private Integer priceMax = null;
    @SerializedName("city")
    private String city = null;
    @SerializedName("category")
    private Long category = null;
    @SerializedName("startDate")
    private Calendar startDate = null;
    @SerializedName("endDate")
    private Calendar endDate = null;

  @ApiModelProperty(value = "")
  public BigDecimal getPage() {
    return page;
  }
  public void setPage(BigDecimal page) {
    this.page = page;
  }

  @ApiModelProperty(value = "")
  public BigDecimal getPageSize() {
    return pageSize;
  }
  public void setPageSize(BigDecimal pageSize) {
    this.pageSize = pageSize;
  }

    @ApiModelProperty(value = "")
    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    @ApiModelProperty(value = "")
    public Integer getPriceMin() {
        return priceMin;
    }
    public void setPriceMin(Integer priceMin) {
        this.priceMin = priceMin;
    }

    @ApiModelProperty(value = "")
    public Integer getPriceMax() {
        return priceMax;
    }
    public void setPriceMax(Integer priceMax) {
        this.priceMax = priceMax;
    }

    @ApiModelProperty(value = "")
    public String getCity() {
        return city;
    }
    public void setCity(String city) {
        this.city = city;
    }

    @ApiModelProperty(value = "")
    public Long getCategory() {
        return category;
    }
    public void setCategory(Long category) {
        this.category = category;
    }

    @ApiModelProperty(value = "")
    public Calendar getStartDate() {
        return startDate;
    }
    public void setStartDate(Calendar startDate) {
        this.startDate = startDate;
    }

    @ApiModelProperty(value = "")
    public Calendar getEndDate() {
        return endDate;
    }
    public void setEndDate(Calendar endDate) {
        this.endDate = endDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ListPostsRequest)) return false;

        ListPostsRequest that = (ListPostsRequest) o;

        if (page != null ? !page.equals(that.page) : that.page != null) return false;
        if (pageSize != null ? !pageSize.equals(that.pageSize) : that.pageSize != null)
            return false;
        if (title != null ? !title.equals(that.title) : that.title != null) return false;
        if (priceMin != null ? !priceMin.equals(that.priceMin) : that.priceMin != null)
            return false;
        if (priceMax != null ? !priceMax.equals(that.priceMax) : that.priceMax != null)
            return false;
        if (city != null ? !city.equals(that.city) : that.city != null) return false;
        if (category != null ? !category.equals(that.category) : that.category != null)
            return false;
        if (startDate != null ? !startDate.equals(that.startDate) : that.startDate != null)
            return false;
        return endDate != null ? endDate.equals(that.endDate) : that.endDate == null;

    }

    @Override
    public int hashCode() {
        int result = page != null ? page.hashCode() : 0;
        result = 31 * result + (pageSize != null ? pageSize.hashCode() : 0);
        result = 31 * result + (title != null ? title.hashCode() : 0);
        result = 31 * result + (priceMin != null ? priceMin.hashCode() : 0);
        result = 31 * result + (priceMax != null ? priceMax.hashCode() : 0);
        result = 31 * result + (city != null ? city.hashCode() : 0);
        result = 31 * result + (category != null ? category.hashCode() : 0);
        result = 31 * result + (startDate != null ? startDate.hashCode() : 0);
        result = 31 * result + (endDate != null ? endDate.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "ListPostsRequest{" +
                "page=" + page +
                ", pageSize=" + pageSize +
                ", title='" + title + '\'' +
                ", priceMin=" + priceMin +
                ", priceMax=" + priceMax +
                ", city=" + city +
                ", category=" + category +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                '}';
    }
}
