/**
 * ServiceFinder API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package hu.bme.onlab.model.post;

import java.math.BigDecimal;
import java.util.List;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class ListPostsResponse  {

  @SerializedName("posts")
  private List<Post> posts = null;
  @SerializedName("totalPosts")
  private BigDecimal totalPosts = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Post> getPosts() {
    return posts;
  }
  public void setPosts(List<Post> posts) {
    this.posts = posts;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getTotalPosts() {
    return totalPosts;
  }
  public void setTotalPosts(BigDecimal totalPosts) {
    this.totalPosts = totalPosts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListPostsResponse listPostsResponse = (ListPostsResponse) o;
    return (posts == null ? listPostsResponse.posts == null : posts.equals(listPostsResponse.posts)) &&
            (totalPosts == null ? listPostsResponse.totalPosts == null : totalPosts.equals(listPostsResponse.totalPosts));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (posts == null ? 0: posts.hashCode());
    result = 31 * result + (totalPosts == null ? 0: totalPosts.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListPostsResponse {\n");

    sb.append("  posts: ").append(posts).append("\n");
    sb.append("  totalPosts: ").append(totalPosts).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}