/**
 * ServiceFinder API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package hu.bme.onlab.model.post;

import java.math.BigDecimal;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class Post  {
  
  @SerializedName("categoryName")
  private String categoryName = null;
  @SerializedName("city")
  private String city = null;
  @SerializedName("creationDateTime")
  private BigDecimal creationDateTime = null;
  @SerializedName("id")
  private BigDecimal id = null;
  @SerializedName("mapUrl")
  private String mapUrl = null;
  @SerializedName("priceMax")
  private BigDecimal priceMax = null;
  @SerializedName("priceMin")
  private BigDecimal priceMin = null;
  @SerializedName("title")
  private String title = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCategoryName() {
    return categoryName;
  }
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getCreationDateTime() {
    return creationDateTime;
  }
  public void setCreationDateTime(BigDecimal creationDateTime) {
    this.creationDateTime = creationDateTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getId() {
    return id;
  }
  public void setId(BigDecimal id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMapUrl() {
    return mapUrl;
  }
  public void setMapUrl(String mapUrl) {
    this.mapUrl = mapUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getPriceMax() {
    return priceMax;
  }
  public void setPriceMax(BigDecimal priceMax) {
    this.priceMax = priceMax;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getPriceMin() {
    return priceMin;
  }
  public void setPriceMin(BigDecimal priceMin) {
    this.priceMin = priceMin;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Post post = (Post) o;
    return (categoryName == null ? post.categoryName == null : categoryName.equals(post.categoryName)) &&
        (city == null ? post.city == null : city.equals(post.city)) &&
        (creationDateTime == null ? post.creationDateTime == null : creationDateTime.equals(post.creationDateTime)) &&
        (id == null ? post.id == null : id.equals(post.id)) &&
        (mapUrl == null ? post.mapUrl == null : mapUrl.equals(post.mapUrl)) &&
        (priceMax == null ? post.priceMax == null : priceMax.equals(post.priceMax)) &&
        (priceMin == null ? post.priceMin == null : priceMin.equals(post.priceMin)) &&
        (title == null ? post.title == null : title.equals(post.title));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (categoryName == null ? 0: categoryName.hashCode());
    result = 31 * result + (city == null ? 0: city.hashCode());
    result = 31 * result + (creationDateTime == null ? 0: creationDateTime.hashCode());
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (mapUrl == null ? 0: mapUrl.hashCode());
    result = 31 * result + (priceMax == null ? 0: priceMax.hashCode());
    result = 31 * result + (priceMin == null ? 0: priceMin.hashCode());
    result = 31 * result + (title == null ? 0: title.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Post {\n");
    
    sb.append("  categoryName: ").append(categoryName).append("\n");
    sb.append("  city: ").append(city).append("\n");
    sb.append("  creationDateTime: ").append(creationDateTime).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  mapUrl: ").append(mapUrl).append("\n");
    sb.append("  priceMax: ").append(priceMax).append("\n");
    sb.append("  priceMin: ").append(priceMin).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
